// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingApi.Infrastructure.Data;

#nullable disable

namespace ParkingApi.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260819202307_VersionBase")]
    partial class VersionBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParkingApi.Domain.Models.AppModule", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ModuleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AppModules", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.CommercialAgreement", b =>
                {
                    b.Property<Guid>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DiscountFixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxHoursApplicable")
                        .HasColumnType("int");

                    b.Property<decimal>("MinPurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.HasKey("AgreementId");

                    b.HasIndex("StoreId");

                    b.ToTable("CommercialAgreements", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.ParkingTicket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeGiven")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("PlateNumber");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("ParkingTickets", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("ResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ResetTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Control total y configuración de tarifas, convenios y usuarios",
                            IsActive = true,
                            Name = "Administrador"
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Operación de terminal POS (Ingreso, Cobro y Turno)",
                            IsActive = true,
                            Name = "Operador"
                        });
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PermissionSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.TicketDiscount", b =>
                {
                    b.Property<Guid>("TicketDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AppliedDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsSynchronized")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ValidatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TicketDiscountId");

                    b.HasIndex("AgreementId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketDiscounts", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@parkflow.com",
                            FullName = "Administrador Principal",
                            IsActive = true,
                            PasswordHash = ".K5vO0Zl8wPz.8c4rV6M7Qe5D2Iu8YQ9pMhU5Zf4OQfe",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operador@parkflow.com",
                            FullName = "Operador de Turno",
                            IsActive = true,
                            PasswordHash = ".K5vO0Zl8wPz.8c4rV6M7Qe5D2Iu8YQ9pMhU5Zf4OQfe",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Username = "operador"
                        });
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.VehicleRate", b =>
                {
                    b.Property<Guid>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("FullDayRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("HourRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MinuteRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("RateId");

                    b.ToTable("VehicleRates", (string)null);

                    b.HasData(
                        new
                        {
                            RateId = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Automóvil / Sedán",
                            FullDayRate = 28000m,
                            GracePeriodMinutes = 15,
                            HourRate = 4000m,
                            IconKey = "IconCar",
                            IsActive = true,
                            MinuteRate = 70m,
                            VehicleType = 0
                        },
                        new
                        {
                            RateId = new Guid("33333333-3333-3333-3333-333333333332"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Motocicleta",
                            FullDayRate = 14000m,
                            GracePeriodMinutes = 15,
                            HourRate = 2000m,
                            IconKey = "IconMotorcycle",
                            IsActive = true,
                            MinuteRate = 35m,
                            VehicleType = 1
                        },
                        new
                        {
                            RateId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Camioneta / SUV",
                            FullDayRate = 35000m,
                            GracePeriodMinutes = 15,
                            HourRate = 5000m,
                            IconKey = "IconSuv",
                            IsActive = true,
                            MinuteRate = 85m,
                            VehicleType = 5
                        },
                        new
                        {
                            RateId = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Furgón / Minibús",
                            FullDayRate = 42000m,
                            GracePeriodMinutes = 15,
                            HourRate = 6000m,
                            IconKey = "IconVan",
                            IsActive = true,
                            MinuteRate = 100m,
                            VehicleType = 3
                        },
                        new
                        {
                            RateId = new Guid("33333333-3333-3333-3333-333333333335"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Vehículo Pesado / Camión",
                            FullDayRate = 70000m,
                            GracePeriodMinutes = 15,
                            HourRate = 10000m,
                            IconKey = "IconTruck",
                            IsActive = true,
                            MinuteRate = 170m,
                            VehicleType = 2
                        });
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.CommercialAgreement", b =>
                {
                    b.HasOne("ParkingApi.Domain.Models.Store", "Store")
                        .WithMany("Agreements")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.PasswordResetToken", b =>
                {
                    b.HasOne("ParkingApi.Domain.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("ParkingApi.Domain.Models.AppModule", "Module")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingApi.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.TicketDiscount", b =>
                {
                    b.HasOne("ParkingApi.Domain.Models.CommercialAgreement", "Agreement")
                        .WithMany("TicketDiscounts")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingApi.Domain.Models.Store", "Store")
                        .WithMany("TicketDiscounts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingApi.Domain.Models.ParkingTicket", "Ticket")
                        .WithMany("Discounts")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agreement");

                    b.Navigation("Store");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.User", b =>
                {
                    b.HasOne("ParkingApi.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.UserSession", b =>
                {
                    b.HasOne("ParkingApi.Domain.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.AppModule", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.CommercialAgreement", b =>
                {
                    b.Navigation("TicketDiscounts");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.ParkingTicket", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.Store", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("TicketDiscounts");
                });

            modelBuilder.Entity("ParkingApi.Domain.Models.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
